const initialMovies = [
  {
    id: 1,
    title: "Inception",
    year: 2010,
    genre: "Sci-Fi",
    rating: 8.8,
    image: "https://picsum.photos/300/400?random=1",
  },
  {
    id: 2,
    title: "The Dark Knight",
    year: 2008,
    genre: "Action",
    rating: 9.0,
    image: "https://picsum.photos/300/400?random=2",
  },
  {
    id: 3,
    title: "Interstellar",
    year: 2014,
    genre: "Sci-Fi",
    rating: 8.6,
    image: "https://picsum.photos/300/400?random=3",
  },
  {
    id: 4,
    title: "The Matrix",
    year: 1999,
    genre: "Sci-Fi",
    rating: 8.7,
    image: "https://picsum.photos/300/400?random=4",
  },
  {
    id: 5,
    title: "Pulp Fiction",
    year: 1994,
    genre: "Crime",
    rating: 8.9,
    image: "https://picsum.photos/300/400?random=5",
  },
  {
    id: 6,
    title: "Fight Club",
    year: 1999,
    genre: "Drama",
    rating: 8.8,
    image: "https://picsum.photos/300/400?random=6",
  },
  {
    id: 7,
    title: "Forrest Gump",
    year: 1994,
    genre: "Drama",
    rating: 8.8,
    image: "https://picsum.photos/300/400?random=7",
  },
  {
    id: 8,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    genre: "Fantasy",
    rating: 8.9,
    image: "https://picsum.photos/300/400?random=8",
  },
  {
    id: 9,
    title: "The Avengers",
    year: 2012,
    genre: "Action",
    rating: 8.0,
    image: "https://picsum.photos/300/400?random=9",
  },
  {
    id: 10,
    title: "Gladiator",
    year: 2000,
    genre: "Action",
    rating: 8.5,
    image: "https://picsum.photos/300/400?random=10",
  },
];

export default initialMovies;
